// <auto-generated>
//     This code was generated  at 2020-07-25 19:14:49.434 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System.Runtime.Serialization;
using ProtoBuf;
namespace could_not_found_the_result_file
{

   
     
}
