// <auto-generated>
//     This code was generated  at 2020-07-25 19:15:03.279 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using System.Net.Mime;
using Microsoft.AspNetCore.Http;
using System.Web.Http;
using System.Runtime.Serialization;
using System.ServiceModel;

using  could_not_found_the_result_file;
namespace mssql.adapter
{
[ServiceContract(Name = "could_not_found_the_result_file")]
public interface IDalService
  {
    
   }

}
