// <auto-generated>
//     This code was generated  at 2020-07-31 21:08:32.942 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using System.Net.Mime;
using Microsoft.AspNetCore.Http;
using System.Web.Http;
using System.Runtime.Serialization;
using System.ServiceModel;

using  beatroot_bo;
namespace mssql.adapter
{
[ServiceContract(Name = "mssql.adapter.BeatrootBoN")]
public interface IDalServiceN
  {
    
      Task<TypesGetResponse> TypesGet(TypesGetRequest req);
      Task<TypesGetV2Response> TypesGetV2(TypesGetV2Request req);
      Task<UserAddResponse> UserAdd(UserAddRequest req);
      Task<UserRoleTypeAddResponse> UserRoleTypeAdd(UserRoleTypeAddRequest req);
      Task<UserRoleTypeGetResponse> UserRoleTypeGet(UserRoleTypeGetRequest req);
      Task<UserRoleTypeRestrictionAddResponse> UserRoleTypeRestrictionAdd(UserRoleTypeRestrictionAddRequest req);
      Task<UserRoleTypeRestrictionDeleteResponse> UserRoleTypeRestrictionDelete(UserRoleTypeRestrictionDeleteRequest req);
      Task<UserRoleTypeRestrictionGetResponse> UserRoleTypeRestrictionGet(UserRoleTypeRestrictionGetRequest req);
      Task<UserRoleTypeRestrictionUpdateResponse> UserRoleTypeRestrictionUpdate(UserRoleTypeRestrictionUpdateRequest req);
      Task<UserRoleTypeUpdateResponse> UserRoleTypeUpdate(UserRoleTypeUpdateRequest req);
      Task<UserSessionCreateResponse> UserSessionCreate(UserSessionCreateRequest req);
      Task<UserSessionInvalidateResponse> UserSessionInvalidate(UserSessionInvalidateRequest req);
      Task<UserSessionVerifyResponse> UserSessionVerify(UserSessionVerifyRequest req);
      Task<UsersGetResponse> UsersGet(UsersGetRequest req);
      Task<UserUpdateResponse> UserUpdate(UserUpdateRequest req);
   }

}
