// <auto-generated>
//     This code was generated  at 2020-07-25 19:14:57.454 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using System.Net.Mime;
using Microsoft.AspNetCore.Http;
using System.Web.Http;

using  could_not_found_the_result_file;
namespace mssql.adapter
{
 
  public partial class DalController:ApiController 
 {
    private DalService dalService;

    public DalController(DalService service)
    {
        dalService=service;
    }

    
   }

}
