

// <auto-generated>
//     This code was generated at 2020-09-04 01:21:13.664 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// package: mssql.adapter.Dui
// file: service.proto

/* tslint:disable */
/* eslint-disable */

"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {};
const service_pb = __importDefault(require("./service_pb"));
const global = Function('return this')();

class ConceptInstanceIdsForUserRequest extends service_pb.default.ConceptInstanceIdsForUserRequest {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getUserid() {
        return this._getNullableValue(super.getUserid(), 1);
    }
    setUserid(value) {
        super.setUserid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLanguagecode() {
        return this._getNullableValue(super.getLanguagecode(), 2);
    }
    setLanguagecode(value) {
        super.setLanguagecode(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getConceptid() {
        return this._getNullableValue(super.getConceptid(), 3);
    }
    setConceptid(value) {
        super.setConceptid(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            userid: msg.getUserid(),
            languagecode: msg.getLanguagecode(),
            conceptid: msg.getConceptid(),
            instanceidsList: (_a = msg.getInstanceidsList()) === null || _a === void 0 ? void 0 : _a.toObject(includeInstance),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.ConceptInstanceIdsForUserRequest = ConceptInstanceIdsForUserRequest;
exports.default.ConceptInstanceIdsForUserRequest = ConceptInstanceIdsForUserRequest;
global.proto.mssql.adapter.Dui.ConceptInstanceIdsForUserRequest = ConceptInstanceIdsForUserRequest;

class TVPinstance_ids extends service_pb.default.TVPinstance_ids {   
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TVPinstance_ids = TVPinstance_ids;
exports.default.TVPinstance_ids = TVPinstance_ids;
global.proto.mssql.adapter.Dui.TVPinstance_ids = TVPinstance_ids;


class ConceptInstanceIdsForUserResponse extends service_pb.default.ConceptInstanceIdsForUserResponse {
}
exports.ConceptInstanceIdsForUserResponse = ConceptInstanceIdsForUserResponse;
exports.default.ConceptInstanceIdsForUserResponse = ConceptInstanceIdsForUserResponse;
global.proto.mssql.adapter.Dui.ConceptInstanceIdsForUserResponse = ConceptInstanceIdsForUserResponse;

class ConceptInstanceIdsForUserItem1 extends service_pb.default.ConceptInstanceIdsForUserItem1 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.ConceptInstanceIdsForUserItem1 = ConceptInstanceIdsForUserItem1;
exports.default.ConceptInstanceIdsForUserItem1 = ConceptInstanceIdsForUserItem1;
global.proto.mssql.adapter.Dui.ConceptInstanceIdsForUserItem1 = ConceptInstanceIdsForUserItem1;
class ConceptInstanceIdsForUserItem2 extends service_pb.default.ConceptInstanceIdsForUserItem2 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.ConceptInstanceIdsForUserItem2 = ConceptInstanceIdsForUserItem2;
exports.default.ConceptInstanceIdsForUserItem2 = ConceptInstanceIdsForUserItem2;
global.proto.mssql.adapter.Dui.ConceptInstanceIdsForUserItem2 = ConceptInstanceIdsForUserItem2;
class NavigateRequest extends service_pb.default.NavigateRequest {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getUserid() {
        return this._getNullableValue(super.getUserid(), 1);
    }
    setUserid(value) {
        super.setUserid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLanguagecode() {
        return this._getNullableValue(super.getLanguagecode(), 2);
    }
    setLanguagecode(value) {
        super.setLanguagecode(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getPath() {
        return this._getNullableValue(super.getPath(), 3);
    }
    setPath(value) {
        super.setPath(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getDisplayoption() {
        return this._getNullableValue(super.getDisplayoption(), 4);
    }
    setDisplayoption(value) {
        super.setDisplayoption(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            userid: msg.getUserid(),
            languagecode: msg.getLanguagecode(),
            path: msg.getPath(),
            displayoption: msg.getDisplayoption(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateRequest = NavigateRequest;
exports.default.NavigateRequest = NavigateRequest;
global.proto.mssql.adapter.Dui.NavigateRequest = NavigateRequest;


class NavigateResponse extends service_pb.default.NavigateResponse {
}
exports.NavigateResponse = NavigateResponse;
exports.default.NavigateResponse = NavigateResponse;
global.proto.mssql.adapter.Dui.NavigateResponse = NavigateResponse;

class NavigateItem1 extends service_pb.default.NavigateItem1 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getConceptid() {
        return this._getNullableValue(super.getConceptid(), 1);
    }
    setConceptid(value) {
        super.setConceptid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getInstanceid() {
        return this._getNullableValue(super.getInstanceid(), 2);
    }
    setInstanceid(value) {
        super.setInstanceid(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getDescription() {
        return this._getNullableValue(super.getDescription(), 3);
    }
    setDescription(value) {
        super.setDescription(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getIsselected() {
        return this._getNullableValue(super.getIsselected(), 4);
    }
    setIsselected(value) {
        super.setIsselected(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            conceptid: msg.getConceptid(),
            instanceid: msg.getInstanceid(),
            description: msg.getDescription(),
            isselected: msg.getIsselected(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateItem1 = NavigateItem1;
exports.default.NavigateItem1 = NavigateItem1;
global.proto.mssql.adapter.Dui.NavigateItem1 = NavigateItem1;
class NavigateItem2 extends service_pb.default.NavigateItem2 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getRelationshipid() {
        return this._getNullableValue(super.getRelationshipid(), 1);
    }
    setRelationshipid(value) {
        super.setRelationshipid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getConceptid() {
        return this._getNullableValue(super.getConceptid(), 2);
    }
    setConceptid(value) {
        super.setConceptid(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getConceptname() {
        return this._getNullableValue(super.getConceptname(), 3);
    }
    setConceptname(value) {
        super.setConceptname(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getConceptdescription() {
        return this._getNullableValue(super.getConceptdescription(), 4);
    }
    setConceptdescription(value) {
        super.setConceptdescription(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    getAllowsmultiselect() {
        return this._getNullableValue(super.getAllowsmultiselect(), 5);
    }
    setAllowsmultiselect(value) {
        super.setAllowsmultiselect(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    getMustbefiltered() {
        return this._getNullableValue(super.getMustbefiltered(), 6);
    }
    setMustbefiltered(value) {
        super.setMustbefiltered(value);
        this._setNullableValue(typeof value === "undefined", 6);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            relationshipid: msg.getRelationshipid(),
            conceptid: msg.getConceptid(),
            conceptname: msg.getConceptname(),
            conceptdescription: msg.getConceptdescription(),
            allowsmultiselect: msg.getAllowsmultiselect(),
            mustbefiltered: msg.getMustbefiltered(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateItem2 = NavigateItem2;
exports.default.NavigateItem2 = NavigateItem2;
global.proto.mssql.adapter.Dui.NavigateItem2 = NavigateItem2;
class NavigateItem3 extends service_pb.default.NavigateItem3 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getActionid() {
        return this._getNullableValue(super.getActionid(), 1);
    }
    setActionid(value) {
        super.setActionid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getActionname() {
        return this._getNullableValue(super.getActionname(), 2);
    }
    setActionname(value) {
        super.setActionname(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getActiondescription() {
        return this._getNullableValue(super.getActiondescription(), 3);
    }
    setActiondescription(value) {
        super.setActiondescription(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getActiontypeid() {
        return this._getNullableValue(super.getActiontypeid(), 4);
    }
    setActiontypeid(value) {
        super.setActiontypeid(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    getActionprocdatabase() {
        return this._getNullableValue(super.getActionprocdatabase(), 5);
    }
    setActionprocdatabase(value) {
        super.setActionprocdatabase(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    getActionprocschema() {
        return this._getNullableValue(super.getActionprocschema(), 6);
    }
    setActionprocschema(value) {
        super.setActionprocschema(value);
        this._setNullableValue(typeof value === "undefined", 6);
        return this;
    }

    getActionprocname() {
        return this._getNullableValue(super.getActionprocname(), 7);
    }
    setActionprocname(value) {
        super.setActionprocname(value);
        this._setNullableValue(typeof value === "undefined", 7);
        return this;
    }

    getIsbulkaction() {
        return this._getNullableValue(super.getIsbulkaction(), 8);
    }
    setIsbulkaction(value) {
        super.setIsbulkaction(value);
        this._setNullableValue(typeof value === "undefined", 8);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            actionid: msg.getActionid(),
            actionname: msg.getActionname(),
            actiondescription: msg.getActiondescription(),
            actiontypeid: msg.getActiontypeid(),
            actionprocdatabase: msg.getActionprocdatabase(),
            actionprocschema: msg.getActionprocschema(),
            actionprocname: msg.getActionprocname(),
            isbulkaction: msg.getIsbulkaction(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateItem3 = NavigateItem3;
exports.default.NavigateItem3 = NavigateItem3;
global.proto.mssql.adapter.Dui.NavigateItem3 = NavigateItem3;
class NavigateItem4 extends service_pb.default.NavigateItem4 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getFilterid() {
        return this._getNullableValue(super.getFilterid(), 1);
    }
    setFilterid(value) {
        super.setFilterid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getFiltername() {
        return this._getNullableValue(super.getFiltername(), 2);
    }
    setFiltername(value) {
        super.setFiltername(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getFilterdescription() {
        return this._getNullableValue(super.getFilterdescription(), 3);
    }
    setFilterdescription(value) {
        super.setFilterdescription(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getFiltertypeid() {
        return this._getNullableValue(super.getFiltertypeid(), 4);
    }
    setFiltertypeid(value) {
        super.setFiltertypeid(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    getFilterprocdatabase() {
        return this._getNullableValue(super.getFilterprocdatabase(), 5);
    }
    setFilterprocdatabase(value) {
        super.setFilterprocdatabase(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    getFilterprocschema() {
        return this._getNullableValue(super.getFilterprocschema(), 6);
    }
    setFilterprocschema(value) {
        super.setFilterprocschema(value);
        this._setNullableValue(typeof value === "undefined", 6);
        return this;
    }

    getFilterprocname() {
        return this._getNullableValue(super.getFilterprocname(), 7);
    }
    setFilterprocname(value) {
        super.setFilterprocname(value);
        this._setNullableValue(typeof value === "undefined", 7);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            filterid: msg.getFilterid(),
            filtername: msg.getFiltername(),
            filterdescription: msg.getFilterdescription(),
            filtertypeid: msg.getFiltertypeid(),
            filterprocdatabase: msg.getFilterprocdatabase(),
            filterprocschema: msg.getFilterprocschema(),
            filterprocname: msg.getFilterprocname(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateItem4 = NavigateItem4;
exports.default.NavigateItem4 = NavigateItem4;
global.proto.mssql.adapter.Dui.NavigateItem4 = NavigateItem4;
class NavigateItem5 extends service_pb.default.NavigateItem5 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getReportid() {
        return this._getNullableValue(super.getReportid(), 1);
    }
    setReportid(value) {
        super.setReportid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getReportname() {
        return this._getNullableValue(super.getReportname(), 2);
    }
    setReportname(value) {
        super.setReportname(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getReportdescription() {
        return this._getNullableValue(super.getReportdescription(), 3);
    }
    setReportdescription(value) {
        super.setReportdescription(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getReporttypeid() {
        return this._getNullableValue(super.getReporttypeid(), 4);
    }
    setReporttypeid(value) {
        super.setReporttypeid(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    getReportprocdatabase() {
        return this._getNullableValue(super.getReportprocdatabase(), 5);
    }
    setReportprocdatabase(value) {
        super.setReportprocdatabase(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    getReportprocschema() {
        return this._getNullableValue(super.getReportprocschema(), 6);
    }
    setReportprocschema(value) {
        super.setReportprocschema(value);
        this._setNullableValue(typeof value === "undefined", 6);
        return this;
    }

    getReportprocname() {
        return this._getNullableValue(super.getReportprocname(), 7);
    }
    setReportprocname(value) {
        super.setReportprocname(value);
        this._setNullableValue(typeof value === "undefined", 7);
        return this;
    }

    getMustbefiltered() {
        return this._getNullableValue(super.getMustbefiltered(), 8);
    }
    setMustbefiltered(value) {
        super.setMustbefiltered(value);
        this._setNullableValue(typeof value === "undefined", 8);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            reportid: msg.getReportid(),
            reportname: msg.getReportname(),
            reportdescription: msg.getReportdescription(),
            reporttypeid: msg.getReporttypeid(),
            reportprocdatabase: msg.getReportprocdatabase(),
            reportprocschema: msg.getReportprocschema(),
            reportprocname: msg.getReportprocname(),
            mustbefiltered: msg.getMustbefiltered(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateItem5 = NavigateItem5;
exports.default.NavigateItem5 = NavigateItem5;
global.proto.mssql.adapter.Dui.NavigateItem5 = NavigateItem5;
class NavigateItem6 extends service_pb.default.NavigateItem6 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 2;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getReportid() {
        return this._getNullableValue(super.getReportid(), 1);
    }
    setReportid(value) {
        super.setReportid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getActionid() {
        return this._getNullableValue(super.getActionid(), 2);
    }
    setActionid(value) {
        super.setActionid(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getActionname() {
        return this._getNullableValue(super.getActionname(), 3);
    }
    setActionname(value) {
        super.setActionname(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getActiondescription() {
        return this._getNullableValue(super.getActiondescription(), 4);
    }
    setActiondescription(value) {
        super.setActiondescription(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    getActiontypeid() {
        return this._getNullableValue(super.getActiontypeid(), 5);
    }
    setActiontypeid(value) {
        super.setActiontypeid(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    getActionprocdatabase() {
        return this._getNullableValue(super.getActionprocdatabase(), 6);
    }
    setActionprocdatabase(value) {
        super.setActionprocdatabase(value);
        this._setNullableValue(typeof value === "undefined", 6);
        return this;
    }

    getActionprocschema() {
        return this._getNullableValue(super.getActionprocschema(), 7);
    }
    setActionprocschema(value) {
        super.setActionprocschema(value);
        this._setNullableValue(typeof value === "undefined", 7);
        return this;
    }

    getActionprocname() {
        return this._getNullableValue(super.getActionprocname(), 8);
    }
    setActionprocname(value) {
        super.setActionprocname(value);
        this._setNullableValue(typeof value === "undefined", 8);
        return this;
    }

    getIsbulkaction() {
        return this._getNullableValue(super.getIsbulkaction(), 9);
    }
    setIsbulkaction(value) {
        super.setIsbulkaction(value);
        this._setNullableValue(typeof value === "undefined", 9);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            reportid: msg.getReportid(),
            actionid: msg.getActionid(),
            actionname: msg.getActionname(),
            actiondescription: msg.getActiondescription(),
            actiontypeid: msg.getActiontypeid(),
            actionprocdatabase: msg.getActionprocdatabase(),
            actionprocschema: msg.getActionprocschema(),
            actionprocname: msg.getActionprocname(),
            isbulkaction: msg.getIsbulkaction(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.NavigateItem6 = NavigateItem6;
exports.default.NavigateItem6 = NavigateItem6;
global.proto.mssql.adapter.Dui.NavigateItem6 = NavigateItem6;
class TestActionVideosEditRequest extends service_pb.default.TestActionVideosEditRequest {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getUserid() {
        return this._getNullableValue(super.getUserid(), 1);
    }
    setUserid(value) {
        super.setUserid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLanguagecode() {
        return this._getNullableValue(super.getLanguagecode(), 2);
    }
    setLanguagecode(value) {
        super.setLanguagecode(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getConceptid() {
        return this._getNullableValue(super.getConceptid(), 3);
    }
    setConceptid(value) {
        super.setConceptid(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getRequest() {
        return this._getNullableValue(super.getRequest(), 5);
    }
    setRequest(value) {
        super.setRequest(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            userid: msg.getUserid(),
            languagecode: msg.getLanguagecode(),
            conceptid: msg.getConceptid(),
            conceptinstanceidsList: (_a = msg.getConceptinstanceidsList()) === null || _a === void 0 ? void 0 : _a.toObject(includeInstance),
            request: msg.getRequest(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestActionVideosEditRequest = TestActionVideosEditRequest;
exports.default.TestActionVideosEditRequest = TestActionVideosEditRequest;
global.proto.mssql.adapter.Dui.TestActionVideosEditRequest = TestActionVideosEditRequest;

class TVPconcept_instance_ids extends service_pb.default.TVPconcept_instance_ids {   
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TVPconcept_instance_ids = TVPconcept_instance_ids;
exports.default.TVPconcept_instance_ids = TVPconcept_instance_ids;
global.proto.mssql.adapter.Dui.TVPconcept_instance_ids = TVPconcept_instance_ids;


class TestActionVideosEditResponse extends service_pb.default.TestActionVideosEditResponse {
}
exports.TestActionVideosEditResponse = TestActionVideosEditResponse;
exports.default.TestActionVideosEditResponse = TestActionVideosEditResponse;
global.proto.mssql.adapter.Dui.TestActionVideosEditResponse = TestActionVideosEditResponse;

class TestActionVideosEditItem1 extends service_pb.default.TestActionVideosEditItem1 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getMetadata() {
        return this._getNullableValue(super.getMetadata(), 1);
    }
    setMetadata(value) {
        super.setMetadata(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            metadata: msg.getMetadata(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestActionVideosEditItem1 = TestActionVideosEditItem1;
exports.default.TestActionVideosEditItem1 = TestActionVideosEditItem1;
global.proto.mssql.adapter.Dui.TestActionVideosEditItem1 = TestActionVideosEditItem1;
class TestActionVideosEditItem2 extends service_pb.default.TestActionVideosEditItem2 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLabel() {
        return this._getNullableValue(super.getLabel(), 2);
    }
    setLabel(value) {
        super.setLabel(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getIsselected() {
        return this._getNullableValue(super.getIsselected(), 3);
    }
    setIsselected(value) {
        super.setIsselected(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getPid() {
        return this._getNullableValue(super.getPid(), 4);
    }
    setPid(value) {
        super.setPid(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
            label: msg.getLabel(),
            isselected: msg.getIsselected(),
            pid: msg.getPid(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestActionVideosEditItem2 = TestActionVideosEditItem2;
exports.default.TestActionVideosEditItem2 = TestActionVideosEditItem2;
global.proto.mssql.adapter.Dui.TestActionVideosEditItem2 = TestActionVideosEditItem2;
class TestActionVideosEditItem3 extends service_pb.default.TestActionVideosEditItem3 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getResponse() {
        return this._getNullableValue(super.getResponse(), 1);
    }
    setResponse(value) {
        super.setResponse(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            response: msg.getResponse(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestActionVideosEditItem3 = TestActionVideosEditItem3;
exports.default.TestActionVideosEditItem3 = TestActionVideosEditItem3;
global.proto.mssql.adapter.Dui.TestActionVideosEditItem3 = TestActionVideosEditItem3;
class TestFilterVideosDurationRangeRequest extends service_pb.default.TestFilterVideosDurationRangeRequest {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getUserid() {
        return this._getNullableValue(super.getUserid(), 1);
    }
    setUserid(value) {
        super.setUserid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLanguagecode() {
        return this._getNullableValue(super.getLanguagecode(), 2);
    }
    setLanguagecode(value) {
        super.setLanguagecode(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getConceptid() {
        return this._getNullableValue(super.getConceptid(), 3);
    }
    setConceptid(value) {
        super.setConceptid(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getRequest() {
        return this._getNullableValue(super.getRequest(), 5);
    }
    setRequest(value) {
        super.setRequest(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            userid: msg.getUserid(),
            languagecode: msg.getLanguagecode(),
            conceptid: msg.getConceptid(),
            conceptinstanceidsList: (_a = msg.getConceptinstanceidsList()) === null || _a === void 0 ? void 0 : _a.toObject(includeInstance),
            request: msg.getRequest(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestFilterVideosDurationRangeRequest = TestFilterVideosDurationRangeRequest;
exports.default.TestFilterVideosDurationRangeRequest = TestFilterVideosDurationRangeRequest;
global.proto.mssql.adapter.Dui.TestFilterVideosDurationRangeRequest = TestFilterVideosDurationRangeRequest;

class TVPconcept_instance_ids extends service_pb.default.TVPconcept_instance_ids {   
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TVPconcept_instance_ids = TVPconcept_instance_ids;
exports.default.TVPconcept_instance_ids = TVPconcept_instance_ids;
global.proto.mssql.adapter.Dui.TVPconcept_instance_ids = TVPconcept_instance_ids;


class TestFilterVideosDurationRangeResponse extends service_pb.default.TestFilterVideosDurationRangeResponse {
}
exports.TestFilterVideosDurationRangeResponse = TestFilterVideosDurationRangeResponse;
exports.default.TestFilterVideosDurationRangeResponse = TestFilterVideosDurationRangeResponse;
global.proto.mssql.adapter.Dui.TestFilterVideosDurationRangeResponse = TestFilterVideosDurationRangeResponse;

class TestFilterVideosDurationRangeItem1 extends service_pb.default.TestFilterVideosDurationRangeItem1 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getMetadata() {
        return this._getNullableValue(super.getMetadata(), 1);
    }
    setMetadata(value) {
        super.setMetadata(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            metadata: msg.getMetadata(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestFilterVideosDurationRangeItem1 = TestFilterVideosDurationRangeItem1;
exports.default.TestFilterVideosDurationRangeItem1 = TestFilterVideosDurationRangeItem1;
global.proto.mssql.adapter.Dui.TestFilterVideosDurationRangeItem1 = TestFilterVideosDurationRangeItem1;
class TestFilterVideosDurationRangeItem2 extends service_pb.default.TestFilterVideosDurationRangeItem2 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLabel() {
        return this._getNullableValue(super.getLabel(), 2);
    }
    setLabel(value) {
        super.setLabel(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getIsselected() {
        return this._getNullableValue(super.getIsselected(), 3);
    }
    setIsselected(value) {
        super.setIsselected(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getPid() {
        return this._getNullableValue(super.getPid(), 4);
    }
    setPid(value) {
        super.setPid(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
            label: msg.getLabel(),
            isselected: msg.getIsselected(),
            pid: msg.getPid(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestFilterVideosDurationRangeItem2 = TestFilterVideosDurationRangeItem2;
exports.default.TestFilterVideosDurationRangeItem2 = TestFilterVideosDurationRangeItem2;
global.proto.mssql.adapter.Dui.TestFilterVideosDurationRangeItem2 = TestFilterVideosDurationRangeItem2;
class TestFilterVideosDurationRangeItem3 extends service_pb.default.TestFilterVideosDurationRangeItem3 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestFilterVideosDurationRangeItem3 = TestFilterVideosDurationRangeItem3;
exports.default.TestFilterVideosDurationRangeItem3 = TestFilterVideosDurationRangeItem3;
global.proto.mssql.adapter.Dui.TestFilterVideosDurationRangeItem3 = TestFilterVideosDurationRangeItem3;
class TestReportCustomersRequest extends service_pb.default.TestReportCustomersRequest {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getUserid() {
        return this._getNullableValue(super.getUserid(), 1);
    }
    setUserid(value) {
        super.setUserid(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLanguagecode() {
        return this._getNullableValue(super.getLanguagecode(), 2);
    }
    setLanguagecode(value) {
        super.setLanguagecode(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getConceptid() {
        return this._getNullableValue(super.getConceptid(), 3);
    }
    setConceptid(value) {
        super.setConceptid(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getRequest() {
        return this._getNullableValue(super.getRequest(), 5);
    }
    setRequest(value) {
        super.setRequest(value);
        this._setNullableValue(typeof value === "undefined", 5);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            userid: msg.getUserid(),
            languagecode: msg.getLanguagecode(),
            conceptid: msg.getConceptid(),
            conceptinstanceidsList: (_a = msg.getConceptinstanceidsList()) === null || _a === void 0 ? void 0 : _a.toObject(includeInstance),
            request: msg.getRequest(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestReportCustomersRequest = TestReportCustomersRequest;
exports.default.TestReportCustomersRequest = TestReportCustomersRequest;
global.proto.mssql.adapter.Dui.TestReportCustomersRequest = TestReportCustomersRequest;

class TVPconcept_instance_ids extends service_pb.default.TVPconcept_instance_ids {   
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TVPconcept_instance_ids = TVPconcept_instance_ids;
exports.default.TVPconcept_instance_ids = TVPconcept_instance_ids;
global.proto.mssql.adapter.Dui.TVPconcept_instance_ids = TVPconcept_instance_ids;


class TestReportCustomersResponse extends service_pb.default.TestReportCustomersResponse {
}
exports.TestReportCustomersResponse = TestReportCustomersResponse;
exports.default.TestReportCustomersResponse = TestReportCustomersResponse;
global.proto.mssql.adapter.Dui.TestReportCustomersResponse = TestReportCustomersResponse;

class TestReportCustomersItem1 extends service_pb.default.TestReportCustomersItem1 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getMetadata() {
        return this._getNullableValue(super.getMetadata(), 1);
    }
    setMetadata(value) {
        super.setMetadata(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            metadata: msg.getMetadata(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestReportCustomersItem1 = TestReportCustomersItem1;
exports.default.TestReportCustomersItem1 = TestReportCustomersItem1;
global.proto.mssql.adapter.Dui.TestReportCustomersItem1 = TestReportCustomersItem1;
class TestReportCustomersItem2 extends service_pb.default.TestReportCustomersItem2 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getId() {
        return this._getNullableValue(super.getId(), 1);
    }
    setId(value) {
        super.setId(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    getLabel() {
        return this._getNullableValue(super.getLabel(), 2);
    }
    setLabel(value) {
        super.setLabel(value);
        this._setNullableValue(typeof value === "undefined", 2);
        return this;
    }

    getIsselected() {
        return this._getNullableValue(super.getIsselected(), 3);
    }
    setIsselected(value) {
        super.setIsselected(value);
        this._setNullableValue(typeof value === "undefined", 3);
        return this;
    }

    getPid() {
        return this._getNullableValue(super.getPid(), 4);
    }
    setPid(value) {
        super.setPid(value);
        this._setNullableValue(typeof value === "undefined", 4);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            id: msg.getId(),
            label: msg.getLabel(),
            isselected: msg.getIsselected(),
            pid: msg.getPid(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestReportCustomersItem2 = TestReportCustomersItem2;
exports.default.TestReportCustomersItem2 = TestReportCustomersItem2;
global.proto.mssql.adapter.Dui.TestReportCustomersItem2 = TestReportCustomersItem2;
class TestReportCustomersItem3 extends service_pb.default.TestReportCustomersItem3 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getResults() {
        return this._getNullableValue(super.getResults(), 1);
    }
    setResults(value) {
        super.setResults(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            results: msg.getResults(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestReportCustomersItem3 = TestReportCustomersItem3;
exports.default.TestReportCustomersItem3 = TestReportCustomersItem3;
global.proto.mssql.adapter.Dui.TestReportCustomersItem3 = TestReportCustomersItem3;
class TestReportCustomersItem4 extends service_pb.default.TestReportCustomersItem4 {
    constructor() {
        super();
        this._areNullablesEnabled = true;
        const nullFields = this._getNullables();
        this.setInternalnullfields(nullFields);
    }
    _getNullables() {
        let nullFields = this.getInternalnullfields_asU8();
        if (!nullFields || nullFields.byteLength === 0) {
            const totalBytes = 1;
            nullFields = new Uint8Array(totalBytes);
            nullFields.fill(255, 0, totalBytes);
        }
        return nullFields;
    }
    _isNullValue(order) {
        if (!this._areNullablesEnabled) {
            return false;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        return (nullFields[n / 8 | 0] & 1 << n % 8) != 0;
    }
    _getNullableValue(value, order) {
        if (this._isNullValue(order)) {
            return undefined;
        }
        return value;
    }
    _setNullableValue(isNullValue, order) {
        if (!this._areNullablesEnabled) {
            return;
        }
        const nullFields = this._getNullables();
        const n = order - 1;
        if (isNullValue) {
            nullFields[n / 8 | 0] |= 1 << n % 8;
        }
        else {
            nullFields[n / 8 | 0] &= ~(1 << n % 8);
        }
        this.setInternalnullfields(nullFields);
    }
    static serializeBinaryToWriter(message, writer) {
        message._areNullablesEnabled = false;
        super.serializeBinaryToWriter(message, writer);
        message._areNullablesEnabled = true;
    }
    static deserializeBinaryFromReader(msg, reader) {
        const nullFields = msg.getInternalnullfields_asU8();
        nullFields.fill(0, 0, nullFields.byteLength);
        msg.setInternalnullfields(nullFields);
        msg._areNullablesEnabled = false;
        super.deserializeBinaryFromReader(msg, reader);
        msg._areNullablesEnabled = true;
        return msg;
    }

    getResults() {
        return this._getNullableValue(super.getResults(), 1);
    }
    setResults(value) {
        super.setResults(value);
        this._setNullableValue(typeof value === "undefined", 1);
        return this;
    }

    static toObject(includeInstance, msg) {
        let _a;
        const obj = {
            results: msg.getResults(),
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    }
}
exports.TestReportCustomersItem4 = TestReportCustomersItem4;
exports.default.TestReportCustomersItem4 = TestReportCustomersItem4;
global.proto.mssql.adapter.Dui.TestReportCustomersItem4 = TestReportCustomersItem4;
