

// <auto-generated>
//     This code was generated at 2020-09-04 01:21:11.572 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// package: mssql.adapter.Dui
// file: service.proto

/* tslint:disable */
/* eslint-disable */

"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const service_grpc_pb = __importDefault(require("./service_grpc_pb"));

exports.DuiServiceClient = service_grpc_pb.default.DuiServiceClient;