

// <auto-generated>
//     This code was generated at 2020-09-04 01:21:10.637 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// package: mssql.adapter.Dui
// file: service.proto

/* tslint:disable */
/* eslint-disable */

import * as grpc from "grpc";
import * as service_grpc from "./service_grpc_pb";
import * as service_pb_overrides from "./service_pb_overrides";

export class DuiServiceClient extends service_grpc.DuiServiceClient {
    //@ts-ignore
    public conceptInstanceIdsForUser(request: service_pb_overrides.ConceptInstanceIdsForUserRequest, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.ConceptInstanceIdsForUserResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public conceptInstanceIdsForUser(request: service_pb_overrides.ConceptInstanceIdsForUserRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.ConceptInstanceIdsForUserResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public conceptInstanceIdsForUser(request: service_pb_overrides.ConceptInstanceIdsForUserRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.ConceptInstanceIdsForUserResponse) => void): grpc.ClientUnaryCall;

    //@ts-ignore
    public navigate(request: service_pb_overrides.NavigateRequest, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.NavigateResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public navigate(request: service_pb_overrides.NavigateRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.NavigateResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public navigate(request: service_pb_overrides.NavigateRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.NavigateResponse) => void): grpc.ClientUnaryCall;

    //@ts-ignore
    public testActionVideosEdit(request: service_pb_overrides.TestActionVideosEditRequest, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestActionVideosEditResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public testActionVideosEdit(request: service_pb_overrides.TestActionVideosEditRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestActionVideosEditResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public testActionVideosEdit(request: service_pb_overrides.TestActionVideosEditRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestActionVideosEditResponse) => void): grpc.ClientUnaryCall;

    //@ts-ignore
    public testFilterVideosDurationRange(request: service_pb_overrides.TestFilterVideosDurationRangeRequest, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestFilterVideosDurationRangeResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public testFilterVideosDurationRange(request: service_pb_overrides.TestFilterVideosDurationRangeRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestFilterVideosDurationRangeResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public testFilterVideosDurationRange(request: service_pb_overrides.TestFilterVideosDurationRangeRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestFilterVideosDurationRangeResponse) => void): grpc.ClientUnaryCall;

    //@ts-ignore
    public testReportCustomers(request: service_pb_overrides.TestReportCustomersRequest, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestReportCustomersResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public testReportCustomers(request: service_pb_overrides.TestReportCustomersRequest, metadata: grpc.Metadata, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestReportCustomersResponse) => void): grpc.ClientUnaryCall;
    //@ts-ignore
    public testReportCustomers(request: service_pb_overrides.TestReportCustomersRequest, metadata: grpc.Metadata, options: Partial<grpc.CallOptions>, callback: (error: grpc.ServiceError | null, response: service_pb_overrides.TestReportCustomersResponse) => void): grpc.ClientUnaryCall;

}