version: "3.7"

services:
  envoy:
    build:
      context: ./envoy
    environment:
      ADMIN_PORT: 90
      NODE_ID: envoy1
      SERVICE_CONTROLLER_ADDRESS: 192.168.1.10
      SERVICE_CONTROLLER_PORT: 5000
    ports:
      - "9090:90"
      - "3000:3000"
